//Localhost
### Get all carss
GET http://localhost:3000/cars

### Get user by id
GET http://localhost:3000/cars/65b283276b4b505eea83ca9c


### create car

POST http://localhost:3000/cars HTTP/1.1
content-type: application/json


{
    "brandName": "Nissan",
    "ownerEmail": "nissan@co.za",
    "model": "2019",
    "name": "Tiffiny",
    "color" : "Red",
    "location": "Cape Town",
    "milage": "1200"
}


### put cars
PUT http://localhost:3000/cars/65a4ff9db1f323ce66385b4a HTTP/1.1

content-type: application/json
{
    "brandName": "Benz",
    "ownerEmail": "benz@gmail.com",
    "model": "2005",
    "name": "Josh",
    "color": "White",
    "location": "Pretoria",
    "milage": "3213"
}

### delete car
DELETE http://localhost:3000/cars/6220b775099269ff7b31ceab HTTP/1.1

// PRODUCTION Deploy
### Get all cars
GET https://cse341-instructor.herokuapp.com/cars


### Get car by id
GET https://cse341-instructor.herokuapp.com/cars/65a4fdceb1f323ce66385b48



### Create car
POST https://cse341-instructor.herokuapp.com/cars HTTP/1.1
content-type: application/json

{
    "brandName": "Nissan",
    "ownerEmail": "nissan@co.za",
    "model": "2019",
    "name": "Tiffiny",
    "color" : "Red",
    "location": "Cape Town",
    "milage": "1200"
}

### PUT car
PUT https://cse341-instructor.herokuapp.com/cars/65b285416b4b505eea83ca9e
 HTTP/1.1
content-type: application/json

{
    "brandName": "Benz",
    "ownerEmail": "benz@gmail.com",
    "model": "2005",
    "name": "Josh",
    "color": "White",
    "location": "Pretoria",
    "milage": "3213"
}

DELETE https://cse341-instructor.herokuapp.com/cars/65b286f76b4b505eea83ca9 HTTP/1.1