//Localhost
### Get all carss
GET http://localhost:3000/cars

### Get user by id
GET http://localhost:3000/cars/65a4ff1eb1f323ce66385b49

### create car

POST http://localhost:3000/cars HTTP/1.1
content-type: application/json


{
    "firstName": "Tapiwar",
    "lastName": "sithole",
    "email": "dbra@education.co.za",
    "favoriteColor": "Yellow",
    "birthday": "Feb 19 2002"
}

### put cars
POST http://localhost:3000/cars/65a4ff9db1f323ce66385b4a HTTP/1.1

content-type: application/json
{
    "firstName": "Jasper",
    "lastName": "Kinm",
    "email": "kim@education.co.za",
    "favoriteColor": "Yellow",
    "birthday": "Sep 12 2003"
}

### delete car
DELETE http://localhost:3000/cars/6220b775099269ff7b31ceab HTTP/1.1

// PRODUCTION Deploy
### Get all cars
GET https://cse341-instructor.herokuapp.com/cars


### Get car by id
GET https://cse341-instructor.herokuapp.com/cars/65a4fdceb1f323ce66385b48



### Create car
POST https://cse341-instructor.herokuapp.com/cars HTTP/1.1
content-type: application/json

{
    "firstName": "Tapiwar",
    "lastName": "sithole",
    "email": "dbra@education.co.za",
    "favoriteColor": "Yellow",
    "birthday": "Feb 19 2002"
}

### PUT car
PUT https://cse341-instructor.herokuapp.com/cars/6220bcb39cd507e920c75a0b HTTP/1.1
content-type: application/json

{
    "firstName": "Jasper",
    "lastName": "Kinm",
    "email": "kim@education.co.za",
    "favoriteColor": "Yellow",
    "birthday": "Sep 12 2003"
}

DELETE https://cse341-instructor.herokuapp.com/cars/65a4ff1eb1f323ce66385b49 HTTP/1.1